.\"     Title: stallone
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 10/21/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "STALLONE" "8" "10/21/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
stallone \- NAT Port\-Mapping Protocol (NAT\-PMP) Gateway Daemon
.SH "SYNOPSIS"
\fIstallone\fR [OPTIONS]
.sp
.SH "DESCRIPTION"
stallone(8) provides computers on directly\-attached private networks with the possibility of having TCP and UDP ports forwarded to them for the purpose of receiving direct connections from machines on the internet.
.sp
.SH "OPTIONS"
.PP
\-c, \-\-check
.RS 4
Check whether a stallone process is already running. Returns 0 (success) if there is one is running and 1 if there is not.
.RE
.PP
\-D, \-\-daemonize
.RS 4
Detach from the terminal and run as a background daemon. Implies
\-s.
.RE
.PP
\-f, \-\-config
.RS 4
File to read configuration from instead of the default
/usr/etc/avahi/natpmd.conf
.RE
.PP
\-h, \-\-help
.RS 4
Provide a list of options.
.RE
.PP
\-k, \-\-kill
.RS 4
Kill an existing stallone process.
.RE
.PP
\-\-no\-chroot
.RS 4
Don't
chroot(2)
the daemon (usually only for debugging).
.RE
.PP
\-s, \-\-syslog
.RS 4
Send log messages to syslog instead of (stderr) (implied by
\-D).
.RE
.PP
\-V, \-\-version
.RS 4
Display stallone's version number and exit.
.RE
.SH "ABOUT"
Stallone: NAT\-PMP Gateway Daemon
.sp
Stallone implements the NAT Port\-Mapping Protocol (NAT\-PMP) allowing machines on a private network to get publicly\-routable TCP and UDP ports automatically.
.sp
.SH "CONFIGURATION"
The default configuration file is /usr/etc/avahi/natpmd.conf, but another may be used by providing the \-\-config (\-f) option at startup.
.sp
The following configuration options are available, shown here with their default values.
.sp
.sp
.RS 4
.nf
[natpmd]
min\-port=30800
max\-port=30999
mapping\-script=/usr/share/stallone/natpmd.action
.fi
.RE
.SH "BUGS"
Please report bugs to \fIhttp://lazypants.org/bugzilla/\fR.
.sp
.SH "SECURITY"
Stallone's architecture is two processes. The main process which maintains state information, and the worker process that handles creating and removing the actual port mappings.
.sp
The main process runs in a chroot as an unprivileged user. The worker process runs as root and is not chrooted \(em it needs to be able to access the machine's firewall configuration (usually iptables). The worker is kept small for easy auditing, and communicates with the main process over a pipe using a simple & strict protocol.
.sp
.SH "SEE ALSO"
Home page: \fIhttp://tedp.id.au/stallone/\fR
.sp
